//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIForRentersLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int AvailabilityID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool Available { get; set; }
        public int UnitID { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
